# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gateway-dev
    image: isl-dsdc.ca.com:5000/apim-gateway/gateway-enterprise:9.4.00
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9443:9443"
      - "8000:8000"
      - "10000:10000"
      - "20000:20000"
      - "65535:65535"
    volumes:
      - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
      - ./build/gateway/gateway-developer-example-0.5.00.gw7:/opt/docker/rc.d/gateway-developer-example-0.5.00.gw7
    secrets:
      - source: license
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
      - source: privateKeys
        target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/privateKeys
    environment:
#      ENV_DEBUG: "true"
#      ENV_DEBUG_PORT: 65535
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "password"
      EXTRA_JAVA_ARGS: "-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
      # passwords
      ENV.PASSWORD.gateway: "7layer"
      # keystore properties
      ENV.PRIVATE_KEY.borjo04: '{ "algorithm": "RSA", "keyPassword": "" }'
      ENV.PRIVATE_KEY.test: '{ "algorithm": "EC", "keyPassword": "" }'
      # ClusterProps
      ENV.PROPERTY.log_levels: |-
        com.l7tech.server.policy.level = FINEST
        com.hazelcast.level = OFF
      # JDBC
      ENV.JDBC_CONNECTION.MySQL: '{
       "driverClass": "com.mysql.jdbc.Driver",
       "jdbcUrl": "jdbc:mysql://joaoborges-laptop.ca.com:3306/ssg",
       "user": "gateway",
       "passwordRef": "gateway",
       "minimumPoolSize": 10,
       "maximumPoolSize": 15,
       "properties": {
         "useSSL": "false"
       }
     }'
      # Cassandras
      ENV.CASSANDRA_CONNECTION.Test: '{
                                      "keyspace": "Test",
                                      "contactPoint": "Test",
                                      "port": 9042,
                                      "username": "test",
                                      "storedPasswordName": "gateway",
                                      "compression": "LZ4",
                                      "ssl": true,
                                      "tlsCiphers": [
                                        "TLS_RSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384",
                                        "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA",
                                        "TLS_RSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_RSA_WITH_AES_256_GCM_SHA384",
                                        "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384",
                                        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
                                        "TLS_RSA_WITH_AES_256_CBC_SHA",
                                        "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                                        "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
                                        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA",
                                        "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA",
                                        "TLS_RSA_WITH_AES_128_CBC_SHA",
                                        "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384",
                                        "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                                        "TLS_RSA_WITH_AES_256_CBC_SHA256",
                                        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
                                        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
                                        "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
                                        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                                        "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
                                        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA",
                                        "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
                                        "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
                                        "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256",
                                        "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384"
                                      ],
                                      "properties": {
                                        "keepAlive": "true"
                                      }
                                    }'
      ENV.CASSANDRA_CONNECTION.Test2: '{
                                        "keyspace": "",
                                         "contactPoint": "Test2",
                                         "port": 9045,
                                         "username": "",
                                         "compression": "NONE",
                                         "ssl": false
                                         }'
      # Certs
      ENV.CERTIFICATE_FILE.www.amazon.com.pem: |-
        -----BEGIN CERTIFICATE-----
        MIIHDDCCBfSgAwIBAgIQAhzeqxvTxO6V+q3g6pUW1DANBgkqhkiG9w0BAQsFADBE
        MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMR4wHAYDVQQDExVE
        aWdpQ2VydCBHbG9iYWwgQ0EgRzIwHhcNMTgwNTA0MDAwMDAwWhcNMTkwNTA1MTIw
        MDAwWjBoMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
        BxMHU2VhdHRsZTEZMBcGA1UEChMQQW1hem9uLmNvbSwgSW5jLjEXMBUGA1UEAxMO
        d3d3LmFtYXpvbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCp
        9EqbKYQgp1P/ugG1Hgwqp1MIVi2q1ZN7j8BtfXw1fPfj+TInkc5sFp5svXzgcGSe
        49lx+YxhhpTsW2EzTrjRdkuqKnQntbStijdiaRBy0/s6L3Aomaa3B+Na88L/AqUd
        nl086UXAi2rljbel7ZeaRVBSIqinBpZC2XCesKaCRJBlCFHfojJUImvAE3xMpCqK
        puk0z02alPW/fWJNE8jdMUDv2KRID6TqpE+xBQ1uIiqyyToj8796XJIoLUQvi9rS
        30Azw7wQRJX7N1YeeLx221LjP12jd9UEUCKmurwAzo3DNEotE1WhJyGKG0gfpOpC
        wEy6jAFNWvUVmQqNjpqnAgMBAAGjggPUMIID0DAfBgNVHSMEGDAWgBQkbist0GqS
        UVElaQGqmkemiedAIDAdBgNVHQ4EFgQUmLGgnZqEj8YaplF5mz8srfbNx24wggEN
        BgNVHREEggEEMIIBAIISaHVkZGxlcy5hbWF6b24uY29tgiFidWNrZXllLXJldGFp
        bC13ZWJzaXRlLmFtYXpvbi5jb22CFW9yaWdpbi13d3cuYW1hem9uLmNvbYINeXAu
        YW1hem9uLmNvbYIMd3d3LmFtem4uY29tgg53d3cuYW1hem9uLmNvbYINdXMuYW1h
        em9uLmNvbYIRdWVkYXRhLmFtYXpvbi5jb22CEWlwaG9uZS5hbWF6b24uY29tgg9o
        b21lLmFtYXpvbi5jb22CFGNvcnBvcmF0ZS5hbWF6b24uY29tghFidXlib3guYW1h
        em9uLmNvbYIIYW16bi5jb22CCmFtYXpvbi5jb20wDgYDVR0PAQH/BAQDAgWgMB0G
        A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB3BgNVHR8EcDBuMDWgM6Axhi9o
        dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxDQUcyLmNybDA1
        oDOgMYYvaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsQ0FH
        Mi5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1sAQEwKjAoBggrBgEFBQcCARYcaHR0
        cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwBAgIwdAYIKwYBBQUHAQEE
        aDBmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wPgYIKwYB
        BQUHMAKGMmh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2Jh
        bENBRzIuY3J0MAkGA1UdEwQCMAAwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgC7
        2d+8H4pxtZOUI5eqkntHOFeVCqtS6BqQlmQ2jh7RhQAAAWMtaS4dAAAEAwBHMEUC
        IQDAlE7F6+zzTPVU7+pC17eEkW59ImwezrE+ZMPmjq1buQIgIis/d1/aQ+3g1vEA
        ArJ/LLq3WpFF7mYWzWZ2ULRtE9cAdgBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkG
        jbIImjfZEwAAAWMtaS67AAAEAwBHMEUCIEDLDiFDyAWdGuSZHxl4XtrTURSVpcXo
        jS1lx9+Uokh/AiEArG385Q/IJc4FZLBJYY+alh3bEtNJx6Mz3KfuerqGrOAwDQYJ
        KoZIhvcNAQELBQADggEBAGApJnFCMXkJz9ajWKLX0NlfpHKuOwnP1eYfQY75Eh2h
        oVPCUlCZsQCvJuH7o/8NCOPpv13VFjGVpdygugxvmAVr9ZgPWvucgVS0QFqUvNkV
        FqmJX2QwOtam61ZMBqklOhEO1e6nXvfyv8c+BVedORMX3gDJUojWWZF1oZQ4pLpu
        TeaYUkWqRA1merQ4D4RxMZY9kmSdPwXZ5cMHkzW94w8PIiwBOqqt5pv9tVYZv1rE
        baHKoyG95oVi/xZ9CduqBM1gTZxMgfl2habJ/IsseQAgwb7p/PQZq1lUec13SIOm
        9cgDKMjzndb/xnOdbed/IfEPjMovmfUVPnqJ80pqZ10=
        -----END CERTIFICATE-----
      ENV.CERTIFICATE.www.amazon.com: '{
        "verifyHostname": false,
        "trustedForSsl": false,
        "trustedAsSamlAttestingEntity": false,
        "trustAnchor": false,
        "revocationCheckingEnabled": false,
        "trustedForSigningClientCerts": false,
        "trustedForSigningServerCerts": false,
        "trustedAsSamlIssuer": false
      }'
      ENV.CERTIFICATE_FILE.*.uol.com.br.pem: |-
        -----BEGIN CERTIFICATE-----
        MIIEWTCCA0GgAwIBAgIQDM77/CvJvYI/2VmdZPpJsjANBgkqhkiG9w0BAQsFADBG
        MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRUwEwYDVQQLEwxTZXJ2ZXIg
        Q0EgMUIxDzANBgNVBAMTBkFtYXpvbjAeFw0xODA0MjQwMDAwMDBaFw0xOTA1MjQx
        MjAwMDBaMBcxFTATBgNVBAMMDCoudW9sLmNvbS5icjCCASIwDQYJKoZIhvcNAQEB
        BQADggEPADCCAQoCggEBAJjW/OeyJRUmEtJFkVZmTKwq2mBF1jSvujzG/d5bcBTd
        VEhj2wim88mDxlUYRTydHXGdZUroedpgZQfcOE2xg6hhj/4HCR5tya8wNnrk+j3f
        z8wIvhxYwTgrEhmn2BEEJjicHkzShcJ6AgXZpN0ddIDyar3K+zJf/O+tDnzD7/7z
        8tZRwJubT05ZVHbXDkBlLkmCN2An0YF69Yh9TDZ2/VP50YDl7OeMlpZSqbYqYyzB
        gsok5wi436xlWm0UqbcP+wHAsPP7ZSbqJubujLujt0dUXoV0Tzp0KH4Bl2FHzWcM
        iNNdUBYKkW16g8K7gHX0mHVmmm8I0DOisTbwzpHNBIECAwEAAaOCAXAwggFsMB8G
        A1UdIwQYMBaAFFmkZgZSoHuVkjyjlAcnlnRb+T3QMB0GA1UdDgQWBBQqcaHaelZU
        bVikUYwKdp/lcKxKvTAXBgNVHREEEDAOggwqLnVvbC5jb20uYnIwDgYDVR0PAQH/
        BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjA7BgNVHR8ENDAy
        MDCgLqAshipodHRwOi8vY3JsLnNjYTFiLmFtYXpvbnRydXN0LmNvbS9zY2ExYi5j
        cmwwIAYDVR0gBBkwFzALBglghkgBhv1sAQIwCAYGZ4EMAQIBMHUGCCsGAQUFBwEB
        BGkwZzAtBggrBgEFBQcwAYYhaHR0cDovL29jc3Auc2NhMWIuYW1hem9udHJ1c3Qu
        Y29tMDYGCCsGAQUFBzAChipodHRwOi8vY3J0LnNjYTFiLmFtYXpvbnRydXN0LmNv
        bS9zY2ExYi5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEAgH6z
        LbZt/5Z/Ycr9POcR4w0vPHCrj5yc7ybJRYUhBM9/c5aGh/Go519oFhUu1AzUDQM1
        672krzqKDvWzoYfTrcNPM3+rc3gC3hvhrQKzJ0xZ3piVT7zFFPNbhnPTr18b4/DT
        JBs4bTfDW8HKPDjeGpCb+HskkZ6on1jVpNF5Qxkgu+u2WZRX77kbzVnD2VqAj5eT
        ApJ5a1B5jeFYkdAOU40duJITxsSLiI9i5A0SLjJdtNezorsvSWx0k8GH02TLuzJV
        JtDk+brrJJ5w2VkN5NEAsKS5C3gjkw66hKoPsHmqAVVu9eV3gD8DjrJVjrnk59c8
        9RwtZD3MIkuu5nMqTg==
        -----END CERTIFICATE-----
      ENV.CERTIFICATE.*.uol.com.br: '{
        "verifyHostname": false,
        "trustedForSsl": false,
        "trustedAsSamlAttestingEntity": false,
        "trustAnchor": false,
        "revocationCheckingEnabled": false,
        "trustedForSigningClientCerts": false,
        "trustedForSigningServerCerts": false,
        "trustedAsSamlIssuer": false
      }'
      ENV.CERTIFICATE_FILE.www.google.com.pem: |-
        -----BEGIN CERTIFICATE-----
        MIIDxzCCAq+gAwIBAgIII8pR0+i7kWEwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UE
        BhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczElMCMGA1UEAxMc
        R29vZ2xlIEludGVybmV0IEF1dGhvcml0eSBHMzAeFw0xODA4MjgxODIzMDBaFw0x
        ODExMjAxODIzMDBaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlh
        MRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKDApHb29nbGUgTExDMRcw
        FQYDVQQDDA53d3cuZ29vZ2xlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
        BG69h/q0VI62C64qtA5497K+HJF6CcMSMDglj0ko5SpdM38ozhtLT4DdnNgbS5V9
        xfZ1A6EOf0N96VFSJG950aSjggFSMIIBTjATBgNVHSUEDDAKBggrBgEFBQcDATAO
        BgNVHQ8BAf8EBAMCB4AwGQYDVR0RBBIwEIIOd3d3Lmdvb2dsZS5jb20waAYIKwYB
        BQUHAQEEXDBaMC0GCCsGAQUFBzAChiFodHRwOi8vcGtpLmdvb2cvZ3NyMi9HVFNH
        SUFHMy5jcnQwKQYIKwYBBQUHMAGGHWh0dHA6Ly9vY3NwLnBraS5nb29nL0dUU0dJ
        QUczMB0GA1UdDgQWBBSh8zGNXn++GBb0M220OTqTpwIw0TAMBgNVHRMBAf8EAjAA
        MB8GA1UdIwQYMBaAFHfCuFCaZ3Z2sS3ChtCDoH6mfrpLMCEGA1UdIAQaMBgwDAYK
        KwYBBAHWeQIFAzAIBgZngQwBAgIwMQYDVR0fBCowKDAmoCSgIoYgaHR0cDovL2Ny
        bC5wa2kuZ29vZy9HVFNHSUFHMy5jcmwwDQYJKoZIhvcNAQELBQADggEBAIqwHvex
        +0f6LtZPaQhD+y/swPde4Lf05qsUH2gckipagPu5MivTFYM7vbtTYWBzjcdIH4vX
        UU/bw8IKdq0tAp6rWNlk008H1LBamTsOz/fzWTkel3VkKSmRk5OESbPcGAGszzjt
        yxhB2vS92C0hKlh7+RrjZtJ1QSmtLhGqhwO75GfQCzp/Yd0UEdWCqg53YcWqtx3+
        cZ612nBT8IkWeELQi9yEfO6RyR5Lki8ccsVQTsP19y9F35XFFNJbZsQs+OhmN5Kz
        n9oJbLJa81eS7Pr0HVdgSMLTSUARwBSG6uHL/RedS3m5dnIQUN4PpAaV6cejT+25
        7wBm1tvqBWx7JjE=
        -----END CERTIFICATE-----
      ENV.CERTIFICATE.www.google.com: '{
        "verifyHostname": false,
        "trustedForSsl": false,
        "trustedAsSamlAttestingEntity": false,
        "trustAnchor": false,
        "revocationCheckingEnabled": false,
        "trustedForSigningClientCerts": false,
        "trustedForSigningServerCerts": false,
        "trustedAsSamlIssuer": false
      }'
      ENV.IDENTITY_PROVIDER.Tacoma MSAD: '{
                                              "type": "BIND_ONLY_LDAP",
                                              "properties": {
                                              },
                                              "identityProviderDetail": {
                                                "serverUrls": [
                                                  "ldaps://10.7.34.21:636"
                                                ],
                                                "useSslClientAuthentication": true,
                                                "bindPatternPrefix": "",
                                                "bindPatternSuffix": ""
                                              }
                                            }'
secrets:
  license:
    file: ./docker/license.xml
  privateKeys:
    file: ./src/main/gateway/config/privateKeys