'[Internal Audit Lookup Policy]':
  path: "gateway-solution/audit-policies/[Internal Audit Lookup Policy]"
  tag: "audit-lookup"
'[Internal Audit Sink Policy]':
  path: "gateway-solution/audit-policies/[Internal Audit Sink Policy]"
  tag: "audit-sink"
Audit Viewer Policy:
  path: "gateway-solution/audit-policies/Audit Viewer Policy"
  tag: "audit-viewer"
Audit Filter Policy:
  path: "gateway-solution/audit-policies/Audit Filter Policy"
  tag: "audit-message-filter"
