Test:
  keyspace: "Test"
  contactPoint: "Test"
  port: 9042
  username: "test"
  storedPasswordName: "gateway"
  compression: "LZ4"
  ssl: true
  tlsCiphers:
  - "TLS_RSA_WITH_AES_128_CBC_SHA256"
  - "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384"
  - "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA"
  - "TLS_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256"
  - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256"
  - "TLS_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
  - "TLS_RSA_WITH_AES_256_CBC_SHA"
  - "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256"
  - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
  - "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA"
  - "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA"
  - "TLS_RSA_WITH_AES_128_CBC_SHA"
  - "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
  - "TLS_RSA_WITH_AES_256_CBC_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"
  - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
  - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
  - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA"
  - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
  - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
  - "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256"
  - "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384"
  properties:
    keepAlive: "true"
Test2:
  keyspace: ""
  contactPoint: "Test2"
  port: 9045
  username: ""
  compression: "NONE"
  ssl: false
