encass-policy:
  policy: "gateway-solution/encass-policy"
  arguments:
  - name: "hello"
    type: "string"
    requireExplicit: true
  - name: "hello-again"
    type: "message"
    requireExplicit: false
  results:
  - name: "goodbye"
    type: "string"
  - name: "goodbye-again"
    type: "message"
