gateway-solution/encass-policy.xml:
  arguments:
  - name: "hello-again"
    type: "message"
  - name: "hello"
    type: "string"
  results:
  - name: "goodbye-again"
    type: "message"
  - name: "goodbye"
    type: "string"
