global-received-policy:
  path: "gateway-solution/global-policies/global-received-policy"
  tag: "message-received"
global-completed-policy:
  path: "gateway-solution/global-policies/global-completed-policy"
  tag: "message-completed"
