Tacoma MSAD:
  type: "BIND_ONLY_LDAP"
  identityProviderDetail:
    serverUrls:
    - "ldaps://10.7.34.21:636"
    useSslClientAuthentication: true
    bindPatternPrefix: ""
    bindPatternSuffix: ""
