background-task-service:
  interfaceName: "com.l7tech.objectmodel.polback.BackgroundTask"
  operations:
  - policy: "gateway-solution/policy-backed-service/a-policy-backed-service.xml"
    operationName: "run"
Metrics:
  interfaceName: "com.l7tech.external.assertions.pbsmel.server.ServiceMetricsProcessor"
  operations:
  - policy: "gateway-solution/policy-backed-service/Metrics.xml"
    operationName: "process"
