gateway-solution/another-service.xml:
  url: "/another-service-example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/db-service.xml:
  url: "/db-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/my-gateway-api.xml:
  url: "/example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
