gateway-solution/another-service:
  url: "/another-service-example"
  policy: "gateway-solution/another-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/db-service:
  url: "/db-service"
  policy: "gateway-solution/db-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/my-gateway-api:
  url: "/example"
  policy: "gateway-solution/my-gateway-api"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/ftp-service:
  url: "/ftp-service"
  policy: "gateway-solution/ftp-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/cassandra-service:
  url: "/cassandra-service"
  policy: "gateway-solution/cassandra-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/soap/PlayerStatsService:
  url: "/playerStatsService"
  policy: "gateway-solution/soap/PlayerStatsService"
  httpMethods:
  - "POST"
  properties: {}
  wsdl:
    soapVersion: "1.1"
    wsdlXml: "<wsdl:definitions targetNamespace=\"http://hugh:8081/axis/services/PlayerStats\"\
      \ xmlns:apachesoap=\"http://xml.apache.org/xml-soap\" xmlns:impl=\"http://hugh:8081/axis/services/PlayerStats\"\
      \ xmlns:intf=\"http://hugh:8081/axis/services/PlayerStats\" xmlns:tns1=\"http://playerstatsws.test.l7tech.com\"\
      \ xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:wsdlsoap=\"http://schemas.xmlsoap.org/wsdl/soap/\"\
      \ xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n<!--WSDL created by Apache\
      \ Axis version: 1.3\nBuilt on Oct 05, 2005 (05:23:37 EDT)-->\n <wsdl:types>\n\
      \  <schema elementFormDefault=\"qualified\" targetNamespace=\"http://playerstatsws.test.l7tech.com\"\
      \ xmlns=\"http://www.w3.org/2001/XMLSchema\">\n   <element name=\"getPhysicalStats\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"playerNumber\"\
      \ type=\"xsd:int\"/>\n      <element name=\"delay\" type=\"xsd:int\"/>\n   \
      \  </sequence>\n    </complexType>\n   </element>\n   <element name=\"getPhysicalStatsResponse\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"getPhysicalStatsReturn\"\
      \ type=\"tns1:PhysicalStats\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <complexType name=\"PhysicalStats\">\n    <sequence>\n     <element name=\"\
      height\" nillable=\"true\" type=\"xsd:string\"/>\n     <element name=\"position\"\
      \ nillable=\"true\" type=\"xsd:string\"/>\n     <element name=\"shoots\" nillable=\"\
      true\" type=\"xsd:string\"/>\n     <element name=\"weight\" type=\"xsd:int\"\
      />\n    </sequence>\n   </complexType>\n   <element name=\"getOffensiveStats\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"playerNumber\"\
      \ type=\"xsd:int\"/>\n      <element name=\"delay\" type=\"xsd:int\"/>\n   \
      \  </sequence>\n    </complexType>\n   </element>\n   <element name=\"getOffensiveStatsResponse\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"getOffensiveStatsReturn\"\
      \ type=\"tns1:OffensiveStats\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <complexType name=\"OffensiveStats\">\n    <sequence>\n     <element name=\"\
      assists\" type=\"xsd:int\"/>\n     <element name=\"gamesPlayed\" type=\"xsd:int\"\
      />\n     <element name=\"goals\" type=\"xsd:int\"/>\n     <element name=\"penaltyMins\"\
      \ type=\"xsd:int\"/>\n     <element name=\"plusMinus\" type=\"xsd:int\"/>\n\
      \     <element name=\"points\" type=\"xsd:int\"/>\n    </sequence>\n   </complexType>\n\
      \   <element name=\"listPlayers\">\n    <complexType>\n     <sequence>\n   \
      \   <element name=\"delay\" type=\"xsd:int\"/>\n     </sequence>\n    </complexType>\n\
      \   </element>\n   <element name=\"listPlayersResponse\">\n    <complexType>\n\
      \     <sequence>\n      <element maxOccurs=\"unbounded\" name=\"listPlayersReturn\"\
      \ type=\"tns1:Player\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <complexType name=\"DraftDetails\">\n    <sequence>\n     <element name=\"\
      pick\" type=\"xsd:int\"/>\n     <element name=\"round\" type=\"xsd:int\"/>\n\
      \     <element name=\"team\" nillable=\"true\" type=\"xsd:string\"/>\n     <element\
      \ name=\"year\" type=\"xsd:int\"/>\n    </sequence>\n   </complexType>\n   <complexType\
      \ name=\"Player\">\n    <sequence>\n     <element name=\"FName\" nillable=\"\
      true\" type=\"xsd:string\"/>\n     <element name=\"LName\" nillable=\"true\"\
      \ type=\"xsd:string\"/>\n     <element name=\"age\" type=\"xsd:int\"/>\n   \
      \  <element name=\"dob\" nillable=\"true\" type=\"xsd:string\"/>\n     <element\
      \ name=\"draftDetails\" nillable=\"true\" type=\"tns1:DraftDetails\"/>\n   \
      \  <element name=\"number\" type=\"xsd:int\"/>\n     <element name=\"offensiveStats\"\
      \ nillable=\"true\" type=\"tns1:OffensiveStats\"/>\n     <element name=\"physicalStats\"\
      \ nillable=\"true\" type=\"tns1:PhysicalStats\"/>\n    </sequence>\n   </complexType>\n\
      \   <element name=\"getDraftDetails\">\n    <complexType>\n     <sequence>\n\
      \      <element name=\"playerNumber\" type=\"xsd:int\"/>\n      <element name=\"\
      delay\" type=\"xsd:int\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <element name=\"getDraftDetailsResponse\">\n    <complexType>\n     <sequence>\n\
      \      <element name=\"getDraftDetailsReturn\" type=\"tns1:DraftDetails\"/>\n\
      \     </sequence>\n    </complexType>\n   </element>\n   <element name=\"getPlayer\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"playerNumber\"\
      \ type=\"xsd:int\"/>\n      <element name=\"delay\" type=\"xsd:int\"/>\n   \
      \  </sequence>\n    </complexType>\n   </element>\n   <element name=\"getPlayerResponse\"\
      >\n    <complexType>\n     <sequence>\n      <element name=\"getPlayerReturn\"\
      \ type=\"tns1:Player\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <element name=\"addPlayer\">\n    <complexType>\n     <sequence>\n     \
      \ <element name=\"player\" type=\"tns1:Player\"/>\n      <element name=\"delay\"\
      \ type=\"xsd:int\"/>\n     </sequence>\n    </complexType>\n   </element>\n\
      \   <element name=\"addPlayerResponse\">\n    <complexType>\n     <sequence>\n\
      \      <element maxOccurs=\"unbounded\" name=\"addPlayerReturn\" type=\"tns1:Player\"\
      />\n     </sequence>\n    </complexType>\n   </element>\n   <element name=\"\
      removePlayer\">\n    <complexType>\n     <sequence>\n      <element name=\"\
      playerNumber\" type=\"xsd:int\"/>\n      <element name=\"delay\" type=\"xsd:int\"\
      />\n     </sequence>\n    </complexType>\n   </element>\n   <element name=\"\
      removePlayerResponse\">\n    <complexType>\n     <sequence>\n      <element\
      \ maxOccurs=\"unbounded\" name=\"removePlayerReturn\" type=\"tns1:Player\"/>\n\
      \     </sequence>\n    </complexType>\n   </element>\n  </schema>\n </wsdl:types>\n\
      \n   <wsdl:message name=\"getPlayerRequest\">\n\n      <wsdl:part element=\"\
      tns1:getPlayer\" name=\"parameters\"/>\n\n   </wsdl:message>\n\n   <wsdl:message\
      \ name=\"getDraftDetailsRequest\">\n\n      <wsdl:part element=\"tns1:getDraftDetails\"\
      \ name=\"parameters\"/>\n\n   </wsdl:message>\n\n   <wsdl:message name=\"getPhysicalStatsResponse\"\
      >\n\n      <wsdl:part element=\"tns1:getPhysicalStatsResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"getOffensiveStatsRequest\"\
      >\n\n      <wsdl:part element=\"tns1:getOffensiveStats\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"getDraftDetailsResponse\"\
      >\n\n      <wsdl:part element=\"tns1:getDraftDetailsResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"addPlayerResponse\">\n\n\
      \      <wsdl:part element=\"tns1:addPlayerResponse\" name=\"parameters\"/>\n\
      \n   </wsdl:message>\n\n   <wsdl:message name=\"getOffensiveStatsResponse\"\
      >\n\n      <wsdl:part element=\"tns1:getOffensiveStatsResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"removePlayerResponse\">\n\
      \n      <wsdl:part element=\"tns1:removePlayerResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"removePlayerRequest\">\n\
      \n      <wsdl:part element=\"tns1:removePlayer\" name=\"parameters\"/>\n\n \
      \  </wsdl:message>\n\n   <wsdl:message name=\"addPlayerRequest\">\n\n      <wsdl:part\
      \ element=\"tns1:addPlayer\" name=\"parameters\"/>\n\n   </wsdl:message>\n\n\
      \   <wsdl:message name=\"getPhysicalStatsRequest\">\n\n      <wsdl:part element=\"\
      tns1:getPhysicalStats\" name=\"parameters\"/>\n\n   </wsdl:message>\n\n   <wsdl:message\
      \ name=\"listPlayersRequest\">\n\n      <wsdl:part element=\"tns1:listPlayers\"\
      \ name=\"parameters\"/>\n\n   </wsdl:message>\n\n   <wsdl:message name=\"getPlayerResponse\"\
      >\n\n      <wsdl:part element=\"tns1:getPlayerResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:message name=\"listPlayersResponse\">\n\
      \n      <wsdl:part element=\"tns1:listPlayersResponse\" name=\"parameters\"\
      />\n\n   </wsdl:message>\n\n   <wsdl:portType name=\"PlayerStats\">\n\n    \
      \  <wsdl:operation name=\"getPhysicalStats\">\n\n         <wsdl:input message=\"\
      impl:getPhysicalStatsRequest\" name=\"getPhysicalStatsRequest\"/>\n\n      \
      \   <wsdl:output message=\"impl:getPhysicalStatsResponse\" name=\"getPhysicalStatsResponse\"\
      />\n\n      </wsdl:operation>\n\n      <wsdl:operation name=\"getOffensiveStats\"\
      >\n\n         <wsdl:input message=\"impl:getOffensiveStatsRequest\" name=\"\
      getOffensiveStatsRequest\"/>\n\n         <wsdl:output message=\"impl:getOffensiveStatsResponse\"\
      \ name=\"getOffensiveStatsResponse\"/>\n\n      </wsdl:operation>\n\n      <wsdl:operation\
      \ name=\"listPlayers\">\n\n         <wsdl:input message=\"impl:listPlayersRequest\"\
      \ name=\"listPlayersRequest\"/>\n\n         <wsdl:output message=\"impl:listPlayersResponse\"\
      \ name=\"listPlayersResponse\"/>\n\n      </wsdl:operation>\n\n      <wsdl:operation\
      \ name=\"getDraftDetails\">\n\n         <wsdl:input message=\"impl:getDraftDetailsRequest\"\
      \ name=\"getDraftDetailsRequest\"/>\n\n         <wsdl:output message=\"impl:getDraftDetailsResponse\"\
      \ name=\"getDraftDetailsResponse\"/>\n\n      </wsdl:operation>\n\n      <wsdl:operation\
      \ name=\"getPlayer\">\n\n         <wsdl:input message=\"impl:getPlayerRequest\"\
      \ name=\"getPlayerRequest\"/>\n\n         <wsdl:output message=\"impl:getPlayerResponse\"\
      \ name=\"getPlayerResponse\"/>\n\n      </wsdl:operation>\n\n      <wsdl:operation\
      \ name=\"addPlayer\">\n\n         <wsdl:input message=\"impl:addPlayerRequest\"\
      \ name=\"addPlayerRequest\"/>\n\n         <wsdl:output message=\"impl:addPlayerResponse\"\
      \ name=\"addPlayerResponse\"/>\n\n      </wsdl:operation>\n\n      <wsdl:operation\
      \ name=\"removePlayer\">\n\n         <wsdl:input message=\"impl:removePlayerRequest\"\
      \ name=\"removePlayerRequest\"/>\n\n         <wsdl:output message=\"impl:removePlayerResponse\"\
      \ name=\"removePlayerResponse\"/>\n\n      </wsdl:operation>\n\n   </wsdl:portType>\n\
      \n   <wsdl:binding name=\"PlayerStatsSoapBinding\" type=\"impl:PlayerStats\"\
      >\n\n      <wsdlsoap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"\
      />\n\n      <wsdl:operation name=\"getPhysicalStats\">\n\n         <wsdlsoap:operation\
      \ soapAction=\"\"/>\n\n         <wsdl:input name=\"getPhysicalStatsRequest\"\
      >\n\n            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:input>\n\
      \n         <wsdl:output name=\"getPhysicalStatsResponse\">\n\n            <wsdlsoap:body\
      \ use=\"literal\"/>\n\n         </wsdl:output>\n\n      </wsdl:operation>\n\n\
      \      <wsdl:operation name=\"getOffensiveStats\">\n\n         <wsdlsoap:operation\
      \ soapAction=\"\"/>\n\n         <wsdl:input name=\"getOffensiveStatsRequest\"\
      >\n\n            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:input>\n\
      \n         <wsdl:output name=\"getOffensiveStatsResponse\">\n\n            <wsdlsoap:body\
      \ use=\"literal\"/>\n\n         </wsdl:output>\n\n      </wsdl:operation>\n\n\
      \      <wsdl:operation name=\"listPlayers\">\n\n         <wsdlsoap:operation\
      \ soapAction=\"\"/>\n\n         <wsdl:input name=\"listPlayersRequest\">\n\n\
      \            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:input>\n\n\
      \         <wsdl:output name=\"listPlayersResponse\">\n\n            <wsdlsoap:body\
      \ use=\"literal\"/>\n\n         </wsdl:output>\n\n      </wsdl:operation>\n\n\
      \      <wsdl:operation name=\"getDraftDetails\">\n\n         <wsdlsoap:operation\
      \ soapAction=\"\"/>\n\n         <wsdl:input name=\"getDraftDetailsRequest\"\
      >\n\n            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:input>\n\
      \n         <wsdl:output name=\"getDraftDetailsResponse\">\n\n            <wsdlsoap:body\
      \ use=\"literal\"/>\n\n         </wsdl:output>\n\n      </wsdl:operation>\n\n\
      \      <wsdl:operation name=\"getPlayer\">\n\n         <wsdlsoap:operation soapAction=\"\
      \"/>\n\n         <wsdl:input name=\"getPlayerRequest\">\n\n            <wsdlsoap:body\
      \ use=\"literal\"/>\n\n         </wsdl:input>\n\n         <wsdl:output name=\"\
      getPlayerResponse\">\n\n            <wsdlsoap:body use=\"literal\"/>\n\n   \
      \      </wsdl:output>\n\n      </wsdl:operation>\n\n      <wsdl:operation name=\"\
      addPlayer\">\n\n         <wsdlsoap:operation soapAction=\"\"/>\n\n         <wsdl:input\
      \ name=\"addPlayerRequest\">\n\n            <wsdlsoap:body use=\"literal\"/>\n\
      \n         </wsdl:input>\n\n         <wsdl:output name=\"addPlayerResponse\"\
      >\n\n            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:output>\n\
      \n      </wsdl:operation>\n\n      <wsdl:operation name=\"removePlayer\">\n\n\
      \         <wsdlsoap:operation soapAction=\"\"/>\n\n         <wsdl:input name=\"\
      removePlayerRequest\">\n\n            <wsdlsoap:body use=\"literal\"/>\n\n \
      \        </wsdl:input>\n\n         <wsdl:output name=\"removePlayerResponse\"\
      >\n\n            <wsdlsoap:body use=\"literal\"/>\n\n         </wsdl:output>\n\
      \n      </wsdl:operation>\n\n   </wsdl:binding>\n\n   <wsdl:service name=\"\
      PlayerStatsService\">\n\n      <wsdl:port binding=\"impl:PlayerStatsSoapBinding\"\
      \ name=\"PlayerStats\">\n\n         <wsdlsoap:address location=\"http://hugh.l7tech.com:8081/axis/services/PlayerStats\"\
      />\n\n      </wsdl:port>\n\n   </wsdl:service>\n\n</wsdl:definitions>"
