gateway-solution/another-service:
  url: "/another-service-example"
  policy: "gateway-solution/another-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/db-service:
  url: "/db-service"
  policy: "gateway-solution/db-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/my-gateway-api:
  url: "/example"
  policy: "gateway-solution/my-gateway-api"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/ftp-service:
  url: "/ftp-service"
  policy: "gateway-solution/ftp-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/cassandra-service:
  url: "/cassandra-service"
  policy: "gateway-solution/cassandra-service"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
gateway-solution/soap/PlayerStatsService:
  url: "/playerStatsService"
  policy: "gateway-solution/soap/PlayerStatsService"
  httpMethods:
  - "POST"
  properties: {}
